### ISSUE TITLE
Error in converter_create(type) : basic_string::resize

### ISSUE THREAD

**Issue by qxde01** [qinwf/ropencc#1]
win 7 32 报错
> cc = converter(T2S)
Error in converter_create(type) : basic_string::resize

**Comment by qinwf** [comment]
Thanks for the report, looking into it.

**Comment by qinwf** [comment]
I push an update. Please test it. I tested it with Win10 32bit R, and works fine now.

**Comment by qxde01** [comment]
It works ，thanks.
